# site settings
title: Trapdoor
subtitle: by Alex Simoes-McArtor
email: alex@alexmcartor.com
description: To display my brain.
baseurl: "/trapdoor" # the subpath of your site, e.g. /blog
url: "https://asimoesmcartor.github.io" # the base hostname & protocol for your site
author: Alex Simoes-McArtor
street_address:
city:
state:
zip_code:
country: United States of America
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/asimoesmcartor
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/mamcartor
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/get_am_photos

# build settings
markdown: kramdown

sass:
  style: compressed
